# Set cache options
set(${PROJECT_NAME}_TESTS OFF CACHE BOOL "Enable tests")
set(${PROJECT_NAME}_FUZZER OFF CACHE BOOL "Enable fuzzing")
set(${PROJECT_NAME}_BENCHMARKS OFF CACHE BOOL "Enable benchmarks")
set(${PROJECT_NAME}_TIDY OFF CACHE BOOL "Enable clang-tidy")
set(${PROJECT_NAME}_IWYU OFF CACHE BOOL "Enable include-what-you-use")
set(${PROJECT_NAME}_SANITIZER_ADDRESS OFF CACHE BOOL "Enable ASAN")
set(${PROJECT_NAME}_SANITIZER_MEMORY OFF CACHE BOOL "Enable MSAN, clones and builds custom libc++")
set(${PROJECT_NAME}_SANITIZER_UB OFF CACHE BOOL "Enable UBSAN")
set(${PROJECT_NAME}_COVERAGE OFF CACHE BOOL "Enable coverage mapping")
set(${PROJECT_NAME}_GCOV OFF CACHE BOOL "Enable gcov coverage mapping")
set(${PROJECT_NAME}_USE_LLD OFF CACHE BOOL "Use llvm linker (only with clang)")
